p8105_hw1_tq2171
================
Tingyu Qian
2024-09-15

# Homework 1

## load the dataset

``` r
# Load the 'penguins' dataset from the 'palmerpenguins' package
data("penguins", package = "palmerpenguins")

# Get the number of rows in the 'penguins' dataset
nrow(penguins)
```

    ## [1] 344

``` r
# Get the number of columns in the 'penguins' dataset
ncol(penguins)
```

    ## [1] 8

``` r
# Display the structure of the 'penguins' dataset, including data types and first few entries
str(penguins)
```

    ## tibble [344 × 8] (S3: tbl_df/tbl/data.frame)
    ##  $ species          : Factor w/ 3 levels "Adelie","Chinstrap",..: 1 1 1 1 1 1 1 1 1 1 ...
    ##  $ island           : Factor w/ 3 levels "Biscoe","Dream",..: 3 3 3 3 3 3 3 3 3 3 ...
    ##  $ bill_length_mm   : num [1:344] 39.1 39.5 40.3 NA 36.7 39.3 38.9 39.2 34.1 42 ...
    ##  $ bill_depth_mm    : num [1:344] 18.7 17.4 18 NA 19.3 20.6 17.8 19.6 18.1 20.2 ...
    ##  $ flipper_length_mm: int [1:344] 181 186 195 NA 193 190 181 195 193 190 ...
    ##  $ body_mass_g      : int [1:344] 3750 3800 3250 NA 3450 3650 3625 4675 3475 4250 ...
    ##  $ sex              : Factor w/ 2 levels "female","male": 2 1 1 NA 1 2 1 2 NA NA ...
    ##  $ year             : int [1:344] 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 ...

``` r
# Calculate the mean of the 'flipper_length_mm' column, excluding any missing values (NA)
mean(penguins$flipper_length_mm, na.rm = TRUE)
```

    ## [1] 200.9152

This is a dataset called “penguins”, it contains 344 observations and 8
variables, which means there are 344 rows and 8 columns. Name and the
type of the 8 variables are the following: species (factor), island
(factor), bill_length_mm (numeric), bill_depth_mm (numeric),
flipper_length_mm (integer), body_mass_g (integer), sex (factor) and the
year (integer). Due to the variable flipper_length_mm contains missing
value, so when we calculate the mean of flipper_length_mm, we need to
drop the missing value, whcih use the na.rm=TRUE, and after that, we can
know the mean of flipper length is 200.9152.

## make the scatterplot

``` r
# Load the ggplot2 library
library(ggplot2)

# Create a scatterplot
scatter_plot<-
  ggplot(data = penguins, aes(x = bill_length_mm, y = flipper_length_mm, colour = species)) +
  geom_point() +
  labs(title = "Scatterplot of Bill Length vs Flipper Length", x = "bill_length_mm", y = "flipper_length_mm") +
  theme_minimal()

# Save the plot to the project directory
ggsave("scatterplot.png", plot = scatter_plot, width = 6, height = 4, dpi = 300)
```

    ## Warning: Removed 2 rows containing missing values or values outside the scale range
    ## (`geom_point()`).

# Homework 2

``` r
# Load the tidyverse package
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ lubridate 1.9.3     ✔ tibble    3.2.1
    ## ✔ purrr     1.0.2     ✔ tidyr     1.3.1
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
# Set a seed for reproducibility
set.seed(123)

# Generate a random sample from a standard normal distribution
random_sample <- rnorm(10)

# Create the data frame with the corrected logical vector
df <- data.frame(
  random_sample = random_sample, # Random sample from standard Normal distribution
  logical_vector = random_sample > 0, # Logical vector indicating if each element of the sample > 0
  character_vector = sample(letters[1:10], 10, replace = TRUE), # Character vector of length 10
  factor_vector = factor(sample(c("Level1", "Level2", "Level3"), 10, replace = TRUE)) # Factor vector with 3 levels
)

print(df)
```

    ##    random_sample logical_vector character_vector factor_vector
    ## 1    -0.56047565          FALSE                i        Level2
    ## 2    -0.23017749          FALSE                i        Level1
    ## 3     1.55870831           TRUE                i        Level3
    ## 4     0.07050839           TRUE                c        Level3
    ## 5     0.12928774           TRUE                h        Level1
    ## 6     1.71506499           TRUE                j        Level3
    ## 7     0.46091621           TRUE                g        Level2
    ## 8    -1.26506123          FALSE                j        Level1
    ## 9    -0.68685285          FALSE                i        Level3
    ## 10   -0.44566197          FALSE                c        Level1

``` r
# Mean of the numeric random sample
mean(df %>% pull(random_sample)) # This will work
```

    ## [1] 0.07462564

``` r
# Mean of the logical vector
mean(df %>% pull(logical_vector)) # This will work (logical values are coerced to numeric: TRUE = 1, FALSE = 0)
```

    ## [1] 0.5

``` r
# Mean of the character vector
mean(df %>% pull(character_vector)) # This will not work (character cannot be coerced to numeric)
```

    ## Warning in mean.default(df %>% pull(character_vector)): argument is not numeric
    ## or logical: returning NA

    ## [1] NA

``` r
# Mean of the factor vector
mean(df %>% pull(factor_vector)) # This will not work (factors are internally stored as integers but have a level attribute)
```

    ## Warning in mean.default(df %>% pull(factor_vector)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

The mean calculation works for the numeric random sample and the logical
vector but fails for the character and factor vectors due to how R
handles different data types. The mean of the numeric random sample
works because the values are inherently numeric, allowing for
straightforward mathematical operations. Similarly, the mean of the
logical vector works because R automatically coerces logical values
(`TRUE` and `FALSE`) into numeric values (`1` and `0`), respectively,
making it possible to compute the mean as the proportion of `TRUE`
values. However, the mean calculation does not work for the character
vector because characters are text data that cannot be directly
converted into numbers; R does not know how to interpret or average text
strings. For the factor vector, while it is stored internally as
integers, it represents categorical data with associated levels. The
levels have meaning as categories, not as numeric values, so taking
their mean does not make sense and will not yield a meaningful result.

``` r
# Coerce logical vector to numeric
numeric_logical <- as.numeric(df$logical_vector)

# Coerce character vector to numeric
numeric_character <- as.numeric(df$character_vector)
```

    ## Warning: NAs introduced by coercion

``` r
# Coerce factor vector to numeric
numeric_factor <- as.numeric(df$factor_vector)
```

The `as.numeric()` function in R successfully converts logical vectors
and factor vectors to numeric form, but it fails to convert character
vectors because of how these data types are internally represented.
Logical vectors consist of `TRUE` and `FALSE` values, which have
straightforward numeric equivalents: `TRUE` is converted to `1` and
`FALSE` to `0`. This simple binary nature allows `as.numeric()` to
perform a direct conversion. Similarly, factor vectors are stored as
integers under the hood, with each factor level corresponding to a
unique integer code. When `as.numeric()` is applied to a factor, it
retrieves these underlying integer codes, making the conversion to
numeric possible. In contrast, character vectors consist of text
strings, which have no inherent numeric representation. R cannot assign
a meaningful number to arbitrary text like “apple” or “dog,” so
`as.numeric()` fails to convert characters and instead returns `NA` with
a warning. This difference highlights why `as.numeric()` works for
logical and factor vectors but not for character vectors.

``` r
# Calculate the mean of logic vector again
mean_numeric_logical <- mean(numeric_logical)  # This will work, calculating the proportion of TRUE values

# Calculate the mean of character vector again
mean_numeric_character <- mean(numeric_character, na.rm = TRUE)  # This will return NA or an error due to NA values

# Calculate the mean of factor vector again
mean_numeric_factor <- mean(numeric_factor)  # This will work, but the result may not be meaningful

# Print the results
print(mean(df %>% pull(random_sample))) 
```

    ## [1] 0.07462564

``` r
print(mean_numeric_logical)    # Proportion of TRUE values
```

    ## [1] 0.5

``` r
print(mean_numeric_character)  # Will be NA
```

    ## [1] NaN

``` r
print(mean_numeric_factor)     # Mean of factor levels' integer codes
```

    ## [1] 2
